### ISSUE TITLE
error when install with rakudobrew in os x

### ISSUE THREAD

**Issue by peczenyj** [tadzik/File-Find#17]
hello

I install today the rakudobrew, moar and panda using this tutorial http://rakudo.org/how-to-get-rakudo/ 
I try to install Task::Star and I got this error several times. not sure if it is one problem in my environment or something else 

https://gist.github.com/peczenyj/0700260e0967ed2fc209

I don't have skills do inspect and understand this problem. if you have some hint it will be helpful also.

version:

> This is Rakudo version 2015.12-60-g37e998d built on MoarVM version 2015.12
> implementing Perl 6.c.

**Comment by daleevans** [comment]
I've got this same issue, but on a fresh Debian jessie instance that I launched solely for the purpose of playing with Perl 6.  The underlying issue seems to be that panda can't detect it as being installed, as this is the panda info output:

$ panda info File::Find
File::Find (version 0.1)
File::Find for Perl 6
State: not installed
Source-url: git://github.com/tadzik/File-Find.git
Support: bugtracker	https://github.com/tadzik/File-Find/issues
source	git://github.com/tadzik/File-Find.git
Provides: File::Find	lib/File/Find.pm
Authors: Tadeusz “tadzik” Sośnierz Dagur Valberg Johansson Elizabeth Mattijsen Filip Sergot GlitchMr Heather isleofmax Moritz Lenz Paul Cochrane Steve Mynott timo Tobias Leich

I'm running this version of perl6:

This is Rakudo version 2015.12-74-gb8a75b9 built on MoarVM version 2015.12
implementing Perl 6.c.

**Comment by daleevans** [comment]
i believe i have got some idea as to what happened.  it seems that the info about what modules were installed in the bootstrap are being put into this bizarro filename that looks like it contains part of an embedded comment or something:

/home/dale/panda/inst#/home/dale/.rakudobrew/moar-nom/install/share/perl6/site/panda/state"

but it should actually be in "/home/dale/.rakudobrew/moar-nom/install/share/perl6/site/panda/state
"

If you copy the appropriate lines from that broken file into the real file, things will start working again.

**Comment by tadzik** [comment]
Yep, that's more of a problem with panda than File::Find – it should not attempt to install a module that's already installed.
Meanwhile, as I took my sweet time to look at my github issues (sorry!), panda is mostly discontinued, deprecated, and [zef](http://github.com/ugexe/zef) should be used instead. Please give that a shot, should work better and have more responsive maintainers :)
